# Site settings
title: RHCSA Study Notes
email: djuber@gmail.com
#Write an awesome description for your new site here. You can edit this
#line in _config.yml. It will appear in your document head meta (for
#Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  This is my personal set of notes on setting up an environment for rhcsa study.
  Since a lot of RHCSA focuses on using client services (NFS, LDAP, etc), there
  will be some amount of RHCE level service setup to get the ability to use a client.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://study.beta-reduction.com" # the base hostname & protocol for your site
twitter_username: danieluber
github_username:  djuber

# Build settings
markdown: kramdown
